### ISSUE TITLE
version 2.2.1 notes

### ISSUE THREAD

**Issue by caissist** [limosoft-de/raffytimelapse#14] opened 2020-04-25 16:22 UTC
- while running installing procedure it is writing into [windows path]/programs (x86) - as a 64-bit application?
- updater procedure doesn't work?!
- missing install archive for current version 2.2.2.0 on Github website
- cannot find language files after installation

**Comment by limosoft-de** [comment] 2020-05-21 17:45
Hi @caissist ,

could you please clarify on the update procedure not working? What exactly isn't working? Which version are you currently using?

**Comment by caissist** [comment] 2020-05-29 12:21
![Raffy Timelapse Updater without progress after 10 min](https://user-images.githubusercontent.com/4838604/83259010-9a6ad080-a1b7-11ea-8532-c3e4ba6a3b90.jpg)
Hi,
> could you please clarify on the update procedure not working? What exactly isn't working? 

Raffy Timelapse Updater routine without any progress after even about 10 min.?!

> Which version are you currently using?

2.2.1.0 as offered here.

Another isssue:
When saving video clip your saving routine is not Windows conform, i.e. path features are not fulfilling Windows standards, e.g. a path to folder "2020.03 Cottbuser Himmel - Garten" doesn't work.

And again: is your offered install archive 64-bit?

P.S. I've created all my timelapse video clips with your software.  :-)

Thanks.

**Comment by limosoft-de** [comment] 2020-05-29 15:04
Hi @caissist,

thank you for your update on this.

Let me try and go through everything mentioned here step by step:

- I will have to check on the installation path issue. As the .NET framework is able to compile any application as "AnyCPU" (meaning it will run as 64-bit on a 64-bit machine and as 32-bit on a 32-bit, while using the same binary) the Installer might be mistaken at this point and select the wrong path on your machine. However, this doesn't mean that the programm won't run as a 64-bit application. I will still check this out, as I agree, that this behaviour is misleading.

- I will also check out the Updater issue, but I am currently not able to reproduce this issue. The update server is hosted by Sourceforge which is known to be slow, however, there should of course eventually be some progress. Could you verify, that you are able to reach the update server manually, by trying a manual download from here: https://sourceforge.net/projects/simpletimelapse/files/RaffyTimelapseInstaller.msi/download

- v2.2.2 is indeed missing on GitHub, thanks for pointing that out. Will work on that in seperate Ticket #16 

- Could you specify on the language files missing? If possible, I would kindly ask you to open a seperate ticket for this and explain in more detail. Again, this is something I am not able to reproduce with the current information.

- As for the "Invalid path issue", this is something already beeing worked on as I had a similar request from another user. I will treat this in #15 

Again, thank you very much for your continued feedback. I am happy to hear, that you choose Raffy Timelapse as your timelapse tool of choice!

**Comment by caissist** [comment] 2020-05-29 15:42
Hi,

> * I will also check out the Updater issue, but I am currently not able to reproduce this issue. The update server is hosted by Sourceforge which is known to be slow, however, there should of course eventually be some progress. Could you verify, that you are able to reach the update server manually, by trying a manual download from here: https://sourceforge.net/projects/simpletimelapse/files/RaffyTimelapseInstaller.msi/download

I did, and successfully.

Thanks.

**Comment by limosoft-de** [comment] 2020-05-29 16:03
That is very interesting indeed. Not sure whats happening there. 

On other news, I am happy to announce that v2.2.2 is now available on GitHub (see #16). Thanks again for pointing that out!

However, the mentioned issue at #15 does not seem to be the same as your export problem. I am indeed able to export into a folder titled "2020.03 Cottbuser Himmel - Garten" using Version 2.2.0 and later. Could you please verify that the issue still occurs using the latest version and if so, provide a screenshot or any additional info?

Thanks in advance.

**Comment by caissist** [comment] 2020-05-30 10:08
Hi,
> On other news, I am happy to announce that v2.2.2 is now available on GitHub (see #16). Thanks again for pointing that out!

Thank you, just downloaded.
> However, the mentioned issue at #15 does not seem to be the same as your export problem. I am indeed able to export into a folder titled "2020.03 Cottbuser Himmel - Garten" using Version 2.2.0 and later. Could you please verify that the issue still occurs using the latest version and if so, provide a screenshot or any additional info?

I just remembered that I stumbled over this path issue while **importing**  photos, not storing - sorry. It worked when working around and importing my photos from a folder as "temp".

**Comment by caissist** [comment] 2020-05-30 12:40
Hi,
I installed version 2.2.2 successfully. 
>Could you specify on the language files missing? If possible, I would kindly ask you to open a seperate ticket for this and explain in more detail. Again, this is something I am not able to reproduce with the current information.

I wish to apologize for that. I looked for a such language file in install folder and didn't find. 
I can confirm now it's working.

Thanks.

**Comment by limosoft-de** [comment] 2020-05-31 11:56
Hi @caissist,

glad that most of your issues where solved by now. As your reported issue was caused during import, rest assured that this will be fixed in #15 with the next release.

I was able to reproduce your mentioned Installer issue, and this will be taken care of in #18. Please feel free to watch that issue for any updates.

Please also feel free to open up a new ticket for the Updater not working, so we can close this general ticket. However, at the moment I am not able to recreate this issue and have no other reported problems with it. Therefor I am suspecting some problems with the network connection at your end currently. Would be happy for any additional info you might have on that.

**Closed as completed** 2020-06-22 18:19 UTC
Labels: other
